postgres:
  username: twenty
  password: twenty
  host: postgres
  port: "5432"
  databases:
    twenty: twenty

redis:
  host: redis
  port: "6379"
  password: ""

appSecret: "9f7c2e8a4d6b1f0a3c5e9b7d2a8c6f1e4b0d9a7c5e3f2b8d6a1c4e0f"

