---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowise-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "3000"
  DATABASE_PATH: "/root/.flowise"
  APIKEY_PATH: "/root/.flowise"
  SECRETKEY_PATH: "/root/.flowise"
  LOG_PATH: "/root/.flowise/logs"
  BLOB_STORAGE_PATH: "/root/.flowise/storage"

  # APIKEY_STORAGE_TYPE: "json" # (json | db)

  NUMBER_OF_PROXIES: "1"
  CORS_ORIGINS: "*"
  IFRAME_ORIGINS: "*"

  DATABASE_TYPE: "postgres"
  DATABASE_PORT: "{{ .Values.postgres.port }}"
  DATABASE_HOST: "{{ .Values.postgres.host }}"
  DATABASE_NAME: "{{ .Values.postgres.databases.flowise }}"
  DATABASE_USER: "{{ .Values.postgres.username }}"
  DATABASE_PASSWORD: "{{ .Values.postgres.password }}"
  # DATABASE_SSL: "true"
  # DATABASE_SSL_KEY_BASE64: "<Self signed certificate in BASE64>"

  SECRETKEY_STORAGE_TYPE: "local" # (local | aws)
  #SECRETKEY_PATH: "/root/.flowise"
  # FLOWISE_SECRETKEY_OVERWRITE: "myencryptionkey"
  # SECRETKEY_AWS_ACCESS_KEY: "<your-access-key>"
  # SECRETKEY_AWS_SECRET_KEY: "<your-secret-key>"
  # SECRETKEY_AWS_REGION: "us-west-2"

  FLOWISE_USERNAME: "{{ .Values.olaresEnv.FLOWISE_USERNAME }}"
  FLOWISE_PASSWORD: "{{ .Values.olaresEnv.FLOWISE_PASSWORD }}"
  # FLOWISE_SECRETKEY_OVERWRITE: "myencryptionkey"
  FLOWISE_FILE_SIZE_LIMIT: "50mb"

  DEBUG: "true"
  LOG_LEVEL: "debug" # (error | warn | info | verbose | debug)
  # TOOL_FUNCTION_BUILTIN_DEP: "crypto,fs"
  # TOOL_FUNCTION_EXTERNAL_DEP: "moment,lodash"

  # LANGCHAIN_TRACING_V2: "true"
  # LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
  # LANGCHAIN_API_KEY: "your_api_key"
  # LANGCHAIN_PROJECT: "your_project"

  # DISABLE_FLOWISE_TELEMETRY: "true"

  # MODEL_LIST_CONFIG_JSON: "/your_model_list_config_file_path"

  # STORAGE_TYPE: "local" # (local | s3)
  # BLOB_STORAGE_PATH: "/your_storage_path/.flowise/storage"
  # S3_STORAGE_BUCKET_NAME: "flowise"
  # S3_STORAGE_ACCESS_KEY_ID: "<your-access-key>"
  # S3_STORAGE_SECRET_ACCESS_KEY: "<your-secret-key>"
  # S3_STORAGE_REGION: "us-west-2"
  # S3_ENDPOINT_URL: "<custom-s3-endpoint-url>"
  # S3_FORCE_PATH_STYLE: "false"

  # SHOW_COMMUNITY_NODES: "true"
  # DISABLED_NODES: "bufferMemory,chatOpenAI" # (comma separated list)

  ######################
  # METRICS COLLECTION
  ######################
  # ENABLE_METRICS: "false"
  # METRICS_PROVIDER: "prometheus" # (prometheus | open_telemetry)
  # METRICS_INCLUDE_NODE_METRICS: "true"
  # METRICS_SERVICE_NAME: "FlowiseAI"

  # METRICS_OPEN_TELEMETRY_METRIC_ENDPOINT: "http://localhost:4318/v1/metrics"
  # METRICS_OPEN_TELEMETRY_PROTOCOL: "http" # (http | grpc | proto)
  # METRICS_OPEN_TELEMETRY_DEBUG: "true"

  ######################
  # GLOBAL AGENT PROXY
  ######################
  # GLOBAL_AGENT_HTTP_PROXY: "CorporateHttpProxyUrl"
  # GLOBAL_AGENT_HTTPS_PROXY: "CorporateHttpsProxyUrl"
  # GLOBAL_AGENT_NO_PROXY: "ExceptionHostsToBypassProxyIfNeeded"

  ######################
  # QUEUE CONFIGURATION
  ######################
  # MODE: "queue" # (queue | main)
  # QUEUE_NAME: "flowise-queue"
  # QUEUE_REDIS_EVENT_STREAM_MAX_LEN: "100000"
  # WORKER_CONCURRENCY: "100000"
  # REDIS_URL: ""
  # REDIS_HOST: "localhost"
  # REDIS_PORT: "6379"
  # REDIS_USERNAME: ""
  # REDIS_PASSWORD: ""
  # REDIS_TLS: ""
  # REDIS_CERT: ""
  # REDIS_KEY: ""
  # REDIS_CA: ""
