{{- $fastgptDomainENV := split "," .Values.domain.fastgpt -}}
{{- $fastgptDomain := index $fastgptDomainENV "_0" -}}
{{- $localDomain := $fastgptDomain -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastgpt-config
  namespace: {{ .Release.Namespace }}
data:
  FE_DOMAIN: "https://{{$fastgptDomain}}"
  DEFAULT_ROOT_PSW: "{{ .Values.olaresEnv.DEFAULT_ROOT_PSW }}"
  AIPROXY_API_ENDPOINT: "http://aiproxy-service:3000"
  DB_MAX_LINK: "30"
  MONGODB_URI: "mongodb://fastgpt:fastgpt@mongo-service:27017/admin?directConnection=true&authSource=admin"
  PG_URL: "postgresql://fastgpt:fastgpt@localhost:5432/postgres"
  SANDBOX_URL: "http://sandbox-service:3001"
  LOG_LEVEL: "debug"
  STORE_LOG_LEVEL: "debug"
  WORKFLOW_MAX_RUN_TIMES: "1000"
  WORKFLOW_MAX_LOOP_TIMES: "100"
  
  USE_IP_LIMIT: "false"
  CHAT_FILE_EXPIRE_TIME: "7"
  WORKFLOW_MAX_LOOP_TIMES: "100"
  WORKFLOW_MAX_RUN_TIMES: "1000"
  STORE_LOG_LEVEL: "warn"
  REDIS_URL: "redis://redis-svc:6379"