{{- $difyDomainENV := split "," .Values.domain.client -}}
{{- $difyDomain := index $difyDomainENV "_0" -}}
{{- $topDomain := regexReplaceAll ".*?([^.]+\\.[^.]+)$" $difyDomain "$1" -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-api-env
  namespace: {{ .Release.Namespace }}
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  ALIYUN_OSS_ACCESS_KEY: "your-access-key"
  ALIYUN_OSS_AUTH_VERSION: "v4"
  ALIYUN_OSS_BUCKET_NAME: "your-bucket-name"
  ALIYUN_OSS_ENDPOINT: "https://oss-ap-southeast-1-internal.aliyuncs.com"
  ALIYUN_OSS_PATH: "your-path"
  ALIYUN_OSS_REGION: "ap-southeast-1"
  ALIYUN_OSS_SECRET_KEY: "your-secret-key"
  ALLOW_EMBED: "false"
  ANALYTICDB_ACCOUNT: "testaccount"
  ANALYTICDB_HOST: "gp-test.aliyuncs.com"
  ANALYTICDB_INSTANCE_ID: "gp-ab123456"
  ANALYTICDB_KEY_ID: "your-ak"
  ANALYTICDB_KEY_SECRET: "your-sk"
  ANALYTICDB_MAX_CONNECTION: "5"
  ANALYTICDB_MIN_CONNECTION: "1"
  ANALYTICDB_NAMESPACE: "dify"
  ANALYTICDB_NAMESPACE_PASSWORD: "difypassword"
  ANALYTICDB_PASSWORD: "testpassword"
  ANALYTICDB_PORT: "5432"
  ANALYTICDB_REGION_ID: "cn-hangzhou"
  API_SENTRY_DSN: ""
  API_SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  API_SENTRY_TRACES_SAMPLE_RATE: "1.0"
  API_TOOL_DEFAULT_CONNECT_TIMEOUT: "10"
  API_TOOL_DEFAULT_READ_TIMEOUT: "60"
  APP_API_URL: ""
  APP_WEB_URL: ""
  APP_MAX_ACTIVE_REQUESTS: "0"
  APP_MAX_EXECUTION_TIME: "1200"
  AZURE_BLOB_ACCOUNT_KEY: "difyai"
  AZURE_BLOB_ACCOUNT_NAME: "difyai"
  AZURE_BLOB_ACCOUNT_URL: "https://<your_account_name>.blob.core.windows.net"
  AZURE_BLOB_CONTAINER_NAME: "difyai-container"
  BAIDU_OBS_ACCESS_KEY: "your-access-key"
  BAIDU_OBS_BUCKET_NAME: "your-bucket-name"
  BAIDU_OBS_ENDPOINT: "your-server-url"
  BAIDU_OBS_SECRET_KEY: "your-secret-key"
  BAIDU_VECTOR_DB_ACCOUNT: "root"
  BAIDU_VECTOR_DB_API_KEY: "dify"
  BAIDU_VECTOR_DB_CONNECTION_TIMEOUT_MS: "30000"
  BAIDU_VECTOR_DB_DATABASE: "dify"
  BAIDU_VECTOR_DB_ENDPOINT: "http://127.0.0.1:5287"
  BAIDU_VECTOR_DB_REPLICAS: "3"
  BAIDU_VECTOR_DB_SHARD: "1"
  BROKER_USE_SSL: "false"
  CELERY_AUTO_SCALE: "false"
  CELERY_BROKER_URL: "redis://:{{ .Values.redis.password }}@redis:6379/0"
  CELERY_MAX_WORKERS: ""
  CELERY_MIN_WORKERS: ""
  CELERY_SENTINEL_MASTER_NAME: ""
  CELERY_SENTINEL_SOCKET_TIMEOUT: "0.1"
  CELERY_USE_SENTINEL: "false"
  CELERY_WORKER_AMOUNT: ""
  CELERY_WORKER_CLASS: ""
  CERTBOT_DOMAIN: "your_domain.com"
  CERTBOT_EMAIL: "your_email@example.com"
  CERTBOT_OPTIONS: ""
  CHECK_UPDATE_URL: "https://updates.dify.ai"
  CHROMA_AUTH_CREDENTIALS: ""
  CHROMA_AUTH_PROVIDER: "chromadb.auth.token_authn.TokenAuthClientProvider"
  CHROMA_DATABASE: "default_database"
  CHROMA_HOST: "127.0.0.1"
  CHROMA_IS_PERSISTENT: "TRUE"
  CHROMA_PORT: "8000"
  CHROMA_SERVER_AUTHN_CREDENTIALS: "difyai123456"
  CHROMA_SERVER_AUTHN_PROVIDER: "chromadb.auth.token_authn.TokenAuthenticationServerProvider"
  CHROMA_TENANT: "default_tenant"
  CODE_EXECUTION_API_KEY: "dify-sandbox"
  CODE_EXECUTION_CONNECT_TIMEOUT: "10"
  CODE_EXECUTION_ENDPOINT: "http://sandbox:8194"
  CODE_EXECUTION_READ_TIMEOUT: "60"
  CODE_EXECUTION_WRITE_TIMEOUT: "10"
  CODE_GENERATION_MAX_TOKENS: "1024"
  CODE_MAX_DEPTH: "5"
  CODE_MAX_NUMBER: "9223372036854775807"
  CODE_MAX_NUMBER_ARRAY_LENGTH: "1000"
  CODE_MAX_OBJECT_ARRAY_LENGTH: "30"
  CODE_MAX_PRECISION: "20"
  CODE_MAX_STRING_ARRAY_LENGTH: "30"
  CODE_MAX_STRING_LENGTH: "80000"
  CODE_MIN_NUMBER: "-9223372036854775808"
  CONSOLE_API_URL: ""
  CONSOLE_CORS_ALLOW_ORIGINS: "*"
  CONSOLE_WEB_URL: ""
  COOKIE_DOMAIN: "{{ $topDomain }}"
  NEXT_PUBLIC_COOKIE_DOMAIN: "1"
  COUCHBASE_BUCKET_NAME: "Embeddings"
  COUCHBASE_CONNECTION_STRING: "couchbase://couchbase-server"
  COUCHBASE_PASSWORD: "password"
  COUCHBASE_SCOPE_NAME: "_default"
  COUCHBASE_USER: "Administrator"
  CREATE_TIDB_SERVICE_JOB_ENABLED: "false"
  CSP_WHITELIST: ""
  DB_DATABASE: "{{ .Values.postgres.databases.dify }}"
  DB_HOST: "{{ .Values.postgres.host }}"
  DB_PASSWORD: "{{ .Values.postgres.password }}"
  DB_PLUGIN_DATABASE: "{{ .Values.postgres.databases.difyplugin }}"
  DB_PORT: "{{ .Values.postgres.port }}"
  DB_USERNAME: "{{ .Values.postgres.username }}"
  DEBUG: "false"
  DEPLOY_ENV: "PRODUCTION"
  DIFY_BIND_ADDRESS: "0.0.0.0"
  DIFY_PORT: "5001"
  ELASTICSEARCH_HOST: "0.0.0.0"
  ELASTICSEARCH_PASSWORD: "elastic"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ENABLE_OTEL: "false"
  ENABLE_REQUEST_LOGGING: "False"
  ENABLE_WEBSITE_FIRECRAWL: "true"
  ENABLE_WEBSITE_JINAREADER: "true"
  ENABLE_WEBSITE_WATERCRAWL: "true"
  ENDPOINT_URL_TEMPLATE: "http://localhost/e/{hook_id}"
  ETCD_AUTO_COMPACTION_MODE: "revision"
  ETCD_AUTO_COMPACTION_RETENTION: "1000"
  ETCD_ENDPOINTS: "etcd:2379"
  ETCD_QUOTA_BACKEND_BYTES: "4294967296"
  ETCD_SNAPSHOT_COUNT: "50000"
  ETL_TYPE: "dify"
  EXPOSE_NGINX_PORT: "80"
  EXPOSE_NGINX_SSL_PORT: "443"
  EXPOSE_PLUGIN_DAEMON_PORT: "5002"
  EXPOSE_PLUGIN_DEBUGGING_HOST: "localhost"
  EXPOSE_PLUGIN_DEBUGGING_PORT: "5003"
  FILES_ACCESS_TIMEOUT: "300"
  FILES_URL: ""
  FLASK_DEBUG: "false"
  FORCE_VERIFYING_SIGNATURE: "true"
  GOOGLE_STORAGE_BUCKET_NAME: "your-bucket-name"
  GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64: ""
  GUNICORN_TIMEOUT: "360"
  HTTP_REQUEST_NODE_MAX_BINARY_SIZE: "10485760"
  HTTP_REQUEST_NODE_MAX_TEXT_SIZE: "1048576"
  HTTP_REQUEST_NODE_SSL_VERIFY: "True"
  HUAWEI_CLOUD_HOSTS: "https://127.0.0.1:9200"
  HUAWEI_CLOUD_PASSWORD: "admin"
  HUAWEI_CLOUD_USER: "admin"
  HUAWEI_OBS_ACCESS_KEY: "your-access-key"
  HUAWEI_OBS_BUCKET_NAME: "your-bucket-name"
  HUAWEI_OBS_SECRET_KEY: "your-secret-key"
  HUAWEI_OBS_SERVER: "your-server-url"
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: "4000"
  INIT_PASSWORD: ""
  INNER_API_KEY_FOR_PLUGIN: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  INVITE_EXPIRY_HOURS: "72"
  KIBANA_PORT: "5601"
  LINDORM_PASSWORD: "lindorm"
  LINDORM_QUERY_TIMEOUT: "1"
  LINDORM_URL: "http://lindorm:30070"
  LINDORM_USERNAME: "lindorm"
  LOG_DATEFORMAT: "%Y-%m-%d %H:%M:%S"
  LOG_FILE: "/app/logs/server.log"
  LOG_FILE_BACKUP_COUNT: "5"
  LOG_FILE_MAX_SIZE: "20"
  LOG_LEVEL: "INFO"
  LOG_TZ: "UTC"
  LOOP_NODE_MAX_COUNT: "100"
  MAIL_DEFAULT_SEND_FROM: {{ .Values.olaresEnv.MAIL_DEFAULT_SEND_FROM | default "noreply@example.com" | quote }}
  MAIL_TYPE: {{ .Values.olaresEnv.MAIL_TYPE | default "smtp" | quote }}
  MARKETPLACE_API_URL: "https://marketplace.dify.ai"
  MARKETPLACE_ENABLED: "true"
  MAX_ITERATIONS_NUM: "99"
  MAX_PARALLEL_LIMIT: "10"
  MAX_SUBMIT_COUNT: "100"
  MAX_TOOLS_NUM: "10"
  MAX_VARIABLE_SIZE: "204800"
  MIGRATION_ENABLED: "true"
  MILVUS_ANALYZER_PARAMS: ""
  MILVUS_AUTHORIZATION_ENABLED: "true"
  MILVUS_DATABASE: ""
  MILVUS_ENABLE_HYBRID_SEARCH: "False"
  MILVUS_PASSWORD: "Milvus"
  MILVUS_TOKEN: ""
  MILVUS_URI: "http://127.0.0.1:19530"
  MILVUS_USER: "root"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_ADDRESS: "minio:9000"
  MINIO_SECRET_KEY: "minioadmin"
  MODE: "api"
  MULTIMODAL_SEND_FORMAT: "base64"
  MYSCALE_DATABASE: "dify"
  MYSCALE_FTS_PARAMS: ""
  MYSCALE_HOST: "myscale"
  MYSCALE_PASSWORD: ""
  MYSCALE_PORT: "8123"
  MYSCALE_USER: "default"
  NGINX_CLIENT_MAX_BODY_SIZE: "15M"
  NGINX_ENABLE_CERTBOT_CHALLENGE: "false"
  NGINX_HTTPS_ENABLED: "false"
  NGINX_KEEPALIVE_TIMEOUT: "65"
  NGINX_PORT: "80"
  NGINX_PROXY_READ_TIMEOUT: "3600s"
  NGINX_PROXY_SEND_TIMEOUT: "3600s"
  NGINX_SERVER_NAME: "_"
  NGINX_SSL_CERT_FILENAME: "dify.crt"
  NGINX_SSL_CERT_KEY_FILENAME: "dify.key"
  NGINX_SSL_PORT: "443"
  NGINX_SSL_PROTOCOLS: "TLSv1.1 TLSv1.2 TLSv1.3"
  NGINX_WORKER_PROCESSES: "auto"
  NOTION_CLIENT_ID: ""
  NOTION_CLIENT_SECRET: ""
  NOTION_INTEGRATION_TYPE: "public"
  NOTION_INTERNAL_SECRET: ""
  OCEANBASE_CLUSTER_NAME: "difyai"
  OCEANBASE_ENABLE_HYBRID_SEARCH: "false"
  OCEANBASE_MEMORY_LIMIT: "6G"
  OCEANBASE_VECTOR_DATABASE: "test"
  OCEANBASE_VECTOR_HOST: "oceanbase"
  OCEANBASE_VECTOR_PASSWORD: "difyai123456"
  OCEANBASE_VECTOR_PORT: "2881"
  OCEANBASE_VECTOR_USER: "root@test"
  OCI_ACCESS_KEY: "your-access-key"
  OCI_BUCKET_NAME: "your-bucket-name"
  OCI_ENDPOINT: "https://your-object-storage-namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com"
  OCI_REGION: "us-ashburn-1"
  OCI_SECRET_KEY: "your-secret-key"
  OPENAI_API_BASE: "https://api.openai.com/v1"
  OPENDAL_FS_ROOT: "storage"
  OPENDAL_SCHEME: "fs"
  OPENGAUSS_DATABASE: "dify"
  OPENGAUSS_ENABLE_PQ: "false"
  OPENGAUSS_HOST: "opengauss"
  OPENGAUSS_MAX_CONNECTION: "5"
  OPENGAUSS_MIN_CONNECTION: "1"
  OPENGAUSS_PASSWORD: "Dify@123"
  OPENGAUSS_PORT: "6600"
  OPENGAUSS_USER: "postgres"
  OPENSEARCH_AUTH_METHOD: "basic"
  OPENSEARCH_AWS_REGION: "ap-southeast-1"
  OPENSEARCH_AWS_SERVICE: "aoss"
  OPENSEARCH_BOOTSTRAP_MEMORY_LOCK: "true"
  OPENSEARCH_DISCOVERY_TYPE: "single-node"
  OPENSEARCH_HOST: "opensearch"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Qazwsxedc!@#123"
  OPENSEARCH_JAVA_OPTS_MAX: "1024m"
  OPENSEARCH_JAVA_OPTS_MIN: "512m"
  OPENSEARCH_MEMLOCK_HARD: "-1"
  OPENSEARCH_MEMLOCK_SOFT: "-1"
  OPENSEARCH_NOFILE_HARD: "65536"
  OPENSEARCH_NOFILE_SOFT: "65536"
  OPENSEARCH_PASSWORD: "admin"
  OPENSEARCH_PORT: "9200"
  OPENSEARCH_SECURE: "true"
  OPENSEARCH_USER: "admin"
  OPENSEARCH_VERIFY_CERTS: "true"
  ORACLE_CHARACTERSET: "AL32UTF8"
  ORACLE_CONFIG_DIR: "/app/api/storage/wallet"
  ORACLE_DSN: "oracle:1521/FREEPDB1"
  ORACLE_IS_AUTONOMOUS: "false"
  ORACLE_PASSWORD: "dify"
  ORACLE_PWD: "Dify123456"
  ORACLE_USER: "dify"
  ORACLE_WALLET_LOCATION: "/app/api/storage/wallet"
  ORACLE_WALLET_PASSWORD: "dify"
  OTEL_BATCH_EXPORT_SCHEDULE_DELAY: "5000"
  OTEL_BATCH_EXPORT_TIMEOUT: "10000"
  OTEL_EXPORTER_OTLP_PROTOCOL: ""
  OTEL_EXPORTER_TYPE: "otlp"
  OTEL_MAX_EXPORT_BATCH_SIZE: "512"
  OTEL_MAX_QUEUE_SIZE: "2048"
  OTEL_METRIC_EXPORT_INTERVAL: "60000"
  OTEL_METRIC_EXPORT_TIMEOUT: "30000"
  OTEL_SAMPLING_RATE: "0.1"
  OTLP_API_KEY: ""
  OTLP_BASE_ENDPOINT: "http://localhost:4318"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  PGUSER: "{{ .Values.postgres.username }}"
  PGVECTOR_DATABASE: "{{ .Values.postgres.databases.dify }}"
  PGVECTOR_HOST: "{{ .Values.postgres.host }}"
  PGVECTOR_MAX_CONNECTION: "5"
  PGVECTOR_MIN_CONNECTION: "1"
  PGVECTOR_PASSWORD: "{{ .Values.postgres.password }}"
  PGVECTOR_PGDATA: ""
  PGVECTOR_PGUSER: "{{ .Values.postgres.username }}"
  PGVECTOR_PORT: "{{ .Values.postgres.port }}"
  PGVECTOR_POSTGRES_DB: "{{ .Values.postgres.databases.dify }}"
  PGVECTOR_POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  PGVECTOR_USER: "{{ .Values.postgres.username }}"
  PGVECTO_RS_DATABASE: "{{ .Values.postgres.databases.dify }}"
  PGVECTO_RS_HOST: "{{ .Values.postgres.host }}"
  PGVECTO_RS_PASSWORD: "{{ .Values.postgres.password }}"
  PGVECTO_RS_PORT: "{{ .Values.postgres.port }}"
  PGVECTO_RS_USER: "{{ .Values.postgres.username }}"
  PIP_MIRROR_URL: ""
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_ID: ""
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_SECRET: ""
  PLUGIN_ALIYUN_OSS_AUTH_VERSION: "v4"
  PLUGIN_ALIYUN_OSS_ENDPOINT: ""
  PLUGIN_ALIYUN_OSS_PATH: ""
  PLUGIN_ALIYUN_OSS_REGION: ""
  PLUGIN_AWS_ACCESS_KEY: ""
  PLUGIN_AWS_REGION: ""
  PLUGIN_AWS_SECRET_KEY: ""
  PLUGIN_AZURE_BLOB_STORAGE_CONNECTION_STRING: ""
  PLUGIN_AZURE_BLOB_STORAGE_CONTAINER_NAME: ""
  PLUGIN_BASED_TOKEN_COUNTING_ENABLED: "false"
  PLUGIN_DAEMON_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  PLUGIN_DAEMON_PORT: "5002"
  PLUGIN_DAEMON_URL: "http://plugin-daemon:5002"
  PLUGIN_INSTALLED_PATH: "plugin"
  PLUGIN_MAX_EXECUTION_TIMEOUT: "600"
  PLUGIN_MAX_PACKAGE_SIZE: "52428800"
  PLUGIN_MEDIA_CACHE_PATH: "assets"
  PLUGIN_PACKAGE_CACHE_PATH: "plugin_packages"
  PLUGIN_PPROF_ENABLED: "false"
  PLUGIN_PYTHON_ENV_INIT_TIMEOUT: "120"
  PLUGIN_REMOTE_INSTALL_HOST: "localhost"
  PLUGIN_REMOTE_INSTALL_PORT: "5003"
  PLUGIN_S3_ENDPOINT: ""
  PLUGIN_S3_USE_AWS: ""
  PLUGIN_S3_USE_AWS_MANAGED_IAM: "false"
  PLUGIN_S3_USE_PATH_STYLE: "false"
  PLUGIN_STORAGE_LOCAL_ROOT: "/app/storage"
  PLUGIN_STORAGE_OSS_BUCKET: ""
  PLUGIN_TENCENT_COS_REGION: ""
  PLUGIN_TENCENT_COS_SECRET_ID: ""
  PLUGIN_TENCENT_COS_SECRET_KEY: ""
  PLUGIN_VOLCENGINE_TOS_ACCESS_KEY: ""
  PLUGIN_VOLCENGINE_TOS_ENDPOINT: ""
  PLUGIN_VOLCENGINE_TOS_REGION: ""
  PLUGIN_VOLCENGINE_TOS_SECRET_KEY: ""
  PLUGIN_WORKING_PATH: "/app/storage/cwd"
  POSITION_PROVIDER_EXCLUDES: ""
  POSITION_PROVIDER_INCLUDES: ""
  POSITION_PROVIDER_PINS: ""
  POSITION_TOOL_EXCLUDES: ""
  POSITION_TOOL_INCLUDES: ""
  POSITION_TOOL_PINS: ""
  POSTGRES_DB: ""
  POSTGRES_EFFECTIVE_CACHE_SIZE: "4096MB"
  POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_PASSWORD: ""
  POSTGRES_SHARED_BUFFERS: "128MB"
  POSTGRES_WORK_MEM: "4MB"
  PROMPT_GENERATION_MAX_TOKENS: "512"
  QDRANT_API_KEY: "difyai123456"
  QDRANT_CLIENT_TIMEOUT: "20"
  QDRANT_GRPC_ENABLED: "false"
  QDRANT_GRPC_PORT: "6334"
  QDRANT_REPLICATION_FACTOR: "1"
  QDRANT_URL: "http://qdrant:6333"
  QUEUE_MONITOR_ALERT_EMAILS: ""
  QUEUE_MONITOR_INTERVAL: "30"
  QUEUE_MONITOR_THRESHOLD: "200"
  REDIS_DB: "0"
  REDIS_HOST: "redis"
  REDIS_PASSWORD: "{{ .Values.redis.password }}"
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_USE_CLUSTERS: "false"
  REDIS_USE_SENTINEL: "false"
  REDIS_USE_SSL: "false"
  REFRESH_TOKEN_EXPIRE_DAYS: "30"
  RELYT_DATABASE: "postgres"
  RELYT_HOST: "db"
  RELYT_PASSWORD: "difyai123456"
  RELYT_PORT: "5432"
  RELYT_USER: "postgres"
  RESEND_API_KEY: "your-resend-api-key"
  RESEND_API_URL: "https://api.resend.com"
  RESET_PASSWORD_TOKEN_EXPIRY_MINUTES: "5"
  S3_ACCESS_KEY: ""
  S3_BUCKET_NAME: "difyai"
  S3_ENDPOINT: ""
  S3_REGION: "us-east-1"
  S3_SECRET_KEY: ""
  S3_USE_AWS_MANAGED_IAM: "false"
  SANDBOX_API_KEY: "dify-sandbox"
  SANDBOX_ENABLE_NETWORK: "true"
  SANDBOX_GIN_MODE: "release"
  SANDBOX_HTTPS_PROXY: "http://ssrfproxy:3128"
  SANDBOX_HTTP_PROXY: "http://ssrfproxy:3128"
  SANDBOX_PORT: "8194"
  SANDBOX_WORKER_TIMEOUT: "15"
  SCARF_NO_ANALYTICS: "true"
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  SERVER_WORKER_AMOUNT: "1"
  SERVER_WORKER_CLASS: "gevent"
  SERVER_WORKER_CONNECTIONS: "10"
  SERVICE_API_URL: "https://{{ $difyDomain }}"
  SMTP_OPPORTUNISTIC_TLS: "false"
  SMTP_PASSWORD: {{ .Values.olaresEnv.SMTP_PASSWORD | default "password" | quote }}
  SMTP_PORT: {{ .Values.olaresEnv.SMTP_PORT | default "465" | quote }}
  SMTP_SERVER: {{ .Values.olaresEnv.SMTP_SERVER | default "smpt.example.com" | quote }}
  SMTP_USERNAME: {{ .Values.olaresEnv.SMTP_USERNAME | default "username" | quote }}
  SMTP_USE_TLS: {{ .Values.olaresEnv.SMTP_USE_TLS | default "true" | quote }}
  SQLALCHEMY_ECHO: "false"
  SQLALCHEMY_POOL_RECYCLE: "3600"
  SQLALCHEMY_POOL_SIZE: "30"
  SSRF_COREDUMP_DIR: "/var/spool/squid"
  SSRF_DEFAULT_CONNECT_TIME_OUT: "5"
  SSRF_DEFAULT_READ_TIME_OUT: "5"
  SSRF_DEFAULT_TIME_OUT: "5"
  SSRF_DEFAULT_WRITE_TIME_OUT: "5"
  SSRF_HTTP_PORT: "3128"
  SSRF_PROXY_HTTPS_URL: "http://ssrfproxy:3128"
  SSRF_PROXY_HTTP_URL: "http://ssrfproxy:3128"
  SSRF_REVERSE_PROXY_PORT: "8194"
  SSRF_SANDBOX_HOST: "sandbox"
  STORAGE_TYPE: "opendal"
  SUPABASE_API_KEY: "your-access-key"
  SUPABASE_BUCKET_NAME: "your-bucket-name"
  SUPABASE_URL: "your-server-url"
  TABLESTORE_ACCESS_KEY_ID: "xxx"
  TABLESTORE_ACCESS_KEY_SECRET: "xxx"
  TABLESTORE_ENDPOINT: "https://instance-name.cn-hangzhou.ots.aliyuncs.com"
  TABLESTORE_INSTANCE_NAME: "instance-name"
  TEMPLATE_TRANSFORM_MAX_LENGTH: "80000"
  TENCENT_COS_BUCKET_NAME: "your-bucket-name"
  TENCENT_COS_REGION: "your-region"
  TENCENT_COS_SCHEME: "your-scheme"
  TENCENT_COS_SECRET_ID: "your-secret-id"
  TENCENT_COS_SECRET_KEY: "your-secret-key"
  TENCENT_VECTOR_DB_API_KEY: "dify"
  TENCENT_VECTOR_DB_DATABASE: "dify"
  TENCENT_VECTOR_DB_ENABLE_HYBRID_SEARCH: "false"
  TENCENT_VECTOR_DB_REPLICAS: "2"
  TENCENT_VECTOR_DB_SHARD: "1"
  TENCENT_VECTOR_DB_TIMEOUT: "30"
  TENCENT_VECTOR_DB_URL: "http://127.0.0.1"
  TENCENT_VECTOR_DB_USERNAME: "dify"
  TEXT_GENERATION_TIMEOUT_MS: "60000"
  TIDB_API_URL: "http://127.0.0.1"
  TIDB_IAM_API_URL: "http://127.0.0.1"
  TIDB_ON_QDRANT_API_KEY: "dify"
  TIDB_ON_QDRANT_CLIENT_TIMEOUT: "20"
  TIDB_ON_QDRANT_GRPC_ENABLED: "false"
  TIDB_ON_QDRANT_GRPC_PORT: "6334"
  TIDB_ON_QDRANT_URL: "http://127.0.0.1"
  TIDB_PRIVATE_KEY: "dify"
  TIDB_PROJECT_ID: "dify"
  TIDB_PUBLIC_KEY: "dify"
  TIDB_REGION: "regions/aws-us-east-1"
  TIDB_SPEND_LIMIT: "100"
  TIDB_VECTOR_DATABASE: "dify"
  TIDB_VECTOR_HOST: "tidb"
  TIDB_VECTOR_PASSWORD: ""
  TIDB_VECTOR_PORT: "4000"
  TIDB_VECTOR_USER: ""
  TOP_K_MAX_VALUE: "10"
  UNSTRUCTURED_API_KEY: ""
  UNSTRUCTURED_API_URL: ""
  UPLOAD_AUDIO_FILE_SIZE_LIMIT: "50"
  UPLOAD_FILE_BATCH_LIMIT: "5"
  UPLOAD_FILE_SIZE_LIMIT: "15"
  UPLOAD_IMAGE_FILE_SIZE_LIMIT: "10"
  UPLOAD_VIDEO_FILE_SIZE_LIMIT: "100"
  UPSTASH_VECTOR_TOKEN: "dify"
  UPSTASH_VECTOR_URL: "https://xxx-vector.upstash.io"
  VASTBASE_DATABASE: "dify"
  VASTBASE_HOST: "vastbase"
  VASTBASE_MAX_CONNECTION: "5"
  VASTBASE_MIN_CONNECTION: "1"
  VASTBASE_PASSWORD: "Difyai123456"
  VASTBASE_PORT: "5432"
  VASTBASE_USER: "dify"
  VECTOR_STORE: "weaviate"
  VIKINGDB_ACCESS_KEY: "your-ak"
  VIKINGDB_CONNECTION_TIMEOUT: "30"
  VIKINGDB_HOST: "api-vikingdb.xxx.volces.com"
  VIKINGDB_REGION: "cn-shanghai"
  VIKINGDB_SCHEMA: "http"
  VIKINGDB_SECRET_KEY: "your-sk"
  VIKINGDB_SOCKET_TIMEOUT: "30"
  VOLCENGINE_TOS_ACCESS_KEY: "your-access-key"
  VOLCENGINE_TOS_BUCKET_NAME: "your-bucket-name"
  VOLCENGINE_TOS_ENDPOINT: "your-server-url"
  VOLCENGINE_TOS_REGION: "your-region"
  VOLCENGINE_TOS_SECRET_KEY: "your-secret-key"
  WEAVIATE_API_KEY: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_APIKEY_ENABLED: "true"
  WEAVIATE_AUTHENTICATION_APIKEY_USERS: "hello@dify.ai"
  WEAVIATE_AUTHORIZATION_ADMINLIST_ENABLED: "true"
  WEAVIATE_AUTHORIZATION_ADMINLIST_USERS: "hello@dify.ai"
  WEAVIATE_CLUSTER_HOSTNAME: "node1"
  WEAVIATE_DEFAULT_VECTORIZER_MODULE: "none"
  WEAVIATE_ENDPOINT: "http://weaviate:8080"
  WEAVIATE_PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  WEAVIATE_QUERY_DEFAULTS_LIMIT: "25"
  WEB_API_CORS_ALLOW_ORIGINS: "*"
  WEB_SENTRY_DSN: ""
  WORKFLOW_CALL_MAX_DEPTH: "5"
  WORKFLOW_FILE_UPLOAD_LIMIT: "10"
  WORKFLOW_MAX_EXECUTION_STEPS: "500"
  WORKFLOW_MAX_EXECUTION_TIME: "1200"
  WORKFLOW_NODE_EXECUTION_STORAGE: "rdbms"
  WORKFLOW_PARALLEL_DEPTH_LIMIT: "3"
  DB_EXTRAS: |-
    keepalives=1&keepalives_idle=30&keepalives_interval=10&keepalives_count=3
