---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: surrealdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: surrealdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: surrealdb
    spec:
      initContainers:
      - name: init-chmod-surrealdb
        image: "docker.io/beclab/aboveos-busybox:1.37.0"
        command:
          - sh
          - '-c'
          - |
            mkdir -p /app-data-root
            chown -R 0:0 /app-data-root || true
            chmod -R 777 /app-data-root || true
        resources: {}
        volumeMounts:
          - name: surrealdbdata
            mountPath: /app-data-root
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      containers:
      - name: surrealdb
        image: "docker.io/beclab/surrealdb-surrealdb:v2.4.1"
        command:
          - /surreal
          - start
          - --log
          - info
          - --user
          - root
          - --pass
          - root
          - rocksdb:/mydata/mydatabase.db
        env:
        - name: SURREAL_EXPERIMENTAL_GRAPHQL
          value: "true"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /mydata
          name: surrealdbdata
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/surrealdb'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/surrealdb'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/surrealdb'
          {{- end }}
          type: DirectoryOrCreate
        name: surrealdbdata
---
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: surrealdb
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: surrealdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opennotebook
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: opennotebook
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opennotebook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: opennotebook
    spec:
      initContainers:
      - name: getconfigfile
        image: "docker.io/beclab/lfnovo-open-notebook:1.4.0"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "if [ ! -f '/app/config/config.toml' ]; then mkdir -p /app/config && touch /app/config/config.toml; fi"]
        volumeMounts:
        - mountPath: /app/config
          name: appconfig
      - name: seed-data
        image: "docker.io/beclab/lfnovo-open-notebook:1.4.0"
        command:
          - sh
          - -c
          - |
            if [ ! -s /mnt/data/db.sqlite ] && [ -f /app/data/db.sqlite ]; then
              echo "Seeding db.sqlite into volume..."
              cp /app/data/db.sqlite /mnt/data/db.sqlite
            fi
        volumeMounts:
          - name: appcache
            mountPath: /mnt/data
      - name: init-chmod-data
        image: "docker.io/beclab/aboveos-busybox:1.37.0"
        command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /app-cache-root
        resources: {}
        volumeMounts:
          - name: app-cache-root
            mountPath: /app-cache-root
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      containers:
      - name: opennotebook
        image: "docker.io/beclab/lfnovo-open-notebook:1.4.0"
        env:
        - name: HOSTNAME
          value: '0.0.0.0'
        {{- if .Values.olaresEnv.PASSWORD }}
        - name: OPEN_NOTEBOOK_PASSWORD
          value: "{{ .Values.olaresEnv.PASSWORD }}"
        {{- else }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: opennotebook-config
        ports:
        - containerPort: 8502
        - containerPort: 5055
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: 50m
            memory: 8Mi
        volumeMounts:
        - mountPath: /app/data
          name: appcache
        - mountPath: /app/config
          name: appconfig
        - mountPath: /app/uploads
          name: appuploads
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/data'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/data'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/data'
          {{- end }}
          type: DirectoryOrCreate
        name: appcache
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/uploads'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/uploads'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/uploads'
          {{- end }}
          type: DirectoryOrCreate
        name: appuploads
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/config'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/config'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook/config'
          {{- end }}
          type: DirectoryOrCreate
        name: appconfig
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/opennotebook'
          {{- end }}
          type: DirectoryOrCreate
        name: app-cache-root
---
apiVersion: v1
kind: Service
metadata:
  name: opennotebook
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: opennotebook
spec:
  ports:
  - name: "8502"
    port: 8502
    targetPort: 8502
  - name: "5055"
    port: 5055
    targetPort: 5055
  selector:
    io.kompose.service: opennotebook

