{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $ollamaclientDomainENV := split "," .Values.domain.ollamaclient -}}
{{- $ollamaclientDomain := index $ollamaclientDomainENV "_0" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-env
  namespace: "{{ .Release.Namespace }}"
data:
  PGID: "1000"
  PUID: "1000"
  TZ: "Etc/UTC"
  GGML_CUDA_DISABLE_GRAPHS: "1"
  OLLAMA_ORIGINS: "*"
  MODEL_NAME: "qwen3:30b-a3b-instruct-2507-q4_K_M"
  
{{- end }}

