{{- $anythingllmDomainENV := split "," .Values.domain.anythingllm -}}
{{- $anythingllmDomain := index $anythingllmDomainENV "_0" -}}
{{- $parts := splitList "." $anythingllmDomain -}}
{{- $n := len $parts -}}
{{- $restDomain := "" -}}
{{- if gt $n 2 -}}
  {{- $restDomain = join "." (slice $parts 2 $n) -}}
{{- end -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anythingllm-config
  namespace: {{ .Release.Namespace }}
data:
  # Base configuration
  UID: "1000"
  GID: "1000"

  DEBUG: "true"
  STORAGE_DIR: "/app/server/storage"

  # LLM settings
  LLM_PROVIDER: "ollama"
  # OLLAMA_BASE_PATH: "http://39975b9a1.{{ .Values.admin }}.{{ $restDomain }}"
  OLLAMA_BASE_PATH: "http://d54536a50.shared.{{ $restDomain }}"

  # Embedding settings
  EMBEDDING_ENGINE: "ollama"
  # EMBEDDING_BASE_PATH: "http://39975b9a1.{{ .Values.admin }}.{{ $restDomain }}"
  EMBEDDING_BASE_PATH: "http://d54536a50.shared.{{ $restDomain }}"

  # Vector database
  VECTOR_DB: "lancedb"

  # Audio processing
  WHISPER_PROVIDER: "local"
  TTS_PROVIDER: "native"

  # Security settings
  PASSWORDMINCHAR: "8"

  TARGET_OCR_LANG: "eng,chi_sim"
