olaresManifest.version: '0.8.1'
olaresManifest.type: app
metadata:
  name: grafana
  appid: grafana
  description: Grafana is a multi-platform open source analytics and interactive visualization web application.
  icon: https://app.cdn.olares.com/appstore/grafana/icon.png
  version: '1.0.7'
  title: Grafana
  categories:
  - Productivity
  - Utilities
permission:
  provider:
  - appName: olares-app
    providerName: dashboard
  appData: true
  appCache: true
spec:
  versionName: 12.1.4
  fullDescription: |
    Grafana is a multi-platform open source analytics and interactive visualization web application.

  developer: grafana
  website: https://grafana.com/
  sourceCode: https://github.com/grafana/grafana
  submitter: Olares
  locale:
  - en-US
  - zh-CN
  doc: https://github.com/grafana/grafana/blob/main/README.md
  license:
  - text: MIT
    url: https://github.com/grafana/grafana?tab=AGPL-3.0-1-ov-file
  requiredMemory: 512Mi
  limitedMemory: 1024Mi
  requiredDisk: 128Mi
  limitedDisk: 256Mi
  requiredCpu: 100m
  limitedCpu: 2000m
  supportArch:
  - amd64
options:
  appScope:
    systemService: true
  allowedOutBoundPorts:
    - 3890
    - 80
    - 443
  dependencies:
  - name: olares
    type: system
    version: '>=1.12.3-0'
entrances:
- name: grafana
  port: 3000
  host: grafana
  title: Grafana
  icon: http://app.cdn.olares.com/appstore/grafana/icon.png
envs:
  - envName: GF_USERNAME
    type: string
    required: true
    editable: false
    regex: '^[\w]{1,}$'
  - envName: GF_PASSWORD
    type: password
    required: true
    editable: false
    regex: '^[\w\-!@#$%^&*()+={}\[\]:,.?~]{1,}$'