olaresManifest.version: '0.11.0'
olaresManifest.type: app
metadata:
  name: grafana
  appid: grafana
  description: Grafana is a multi-platform open source analytics and interactive visualization web application.
  icon: https://app.cdn.olares.com/appstore/grafana/icon.png
  version: '1.0.8'
  title: Grafana
  categories:
  - Productivity
  - Utilities
permission:
  provider:
  - appName: olares-app
    providerName: dashboard
  appData: true
  appCache: true
spec:
  versionName: 12.1.4
  fullDescription: |
    Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data-driven culture:

    Visualizations: Fast and flexible client side graphs with a multitude of options. Panel plugins offer many different ways to visualize metrics and logs.
    Dynamic Dashboards: Create dynamic & reusable dashboards with template variables that appear as dropdowns at the top of the dashboard.
    Explore Metrics: Explore your data through ad-hoc queries and dynamic drilldown. Split view and compare different time ranges, queries and data sources side by side.
    Explore Logs: Experience the magic of switching from metrics to logs with preserved label filters. Quickly search through all your logs or streaming them live.
    Alerting: Visually define alert rules for your most important metrics. Grafana will continuously evaluate and send notifications to systems like Slack, PagerDuty, VictorOps, OpsGenie.
    Mixed Data Sources: Mix different data sources in the same graph! You can specify a data source on a per-query basis. This works for even custom datasources.
  developer: grafana
  website: https://grafana.com/
  sourceCode: https://github.com/grafana/grafana
  submitter: Olares
  locale:
  - en-US
  - zh-CN
  doc: https://github.com/grafana/grafana/blob/main/README.md
  license:
  - text: MIT
    url: https://github.com/grafana/grafana?tab=AGPL-3.0-1-ov-file
  requiredMemory: 512Mi
  limitedMemory: 1024Mi
  requiredDisk: 128Mi
  limitedDisk: 256Mi
  requiredCpu: 100m
  limitedCpu: 2000m
  supportArch:
  - amd64
  onlyAdmin: true
options:
  appScope:
    systemService: true
  allowedOutBoundPorts:
    - 3890
    - 80
    - 443
  dependencies:
  - name: olares
    type: system
    version: '>=1.12.3-0'
entrances:
- name: grafana
  port: 3000
  host: grafana
  title: Grafana
  icon: http://app.cdn.olares.com/appstore/grafana/icon.png
envs:
  - envName: GF_USERNAME
    type: string
    required: true
    editable: false
    regex: '^[\w]{1,}$'
  - envName: GF_PASSWORD
    type: password
    required: true
    editable: false
    regex: '^[\w\-!@#$%^&*()+={}\[\]:,.?~]{1,}$'