apiVersion: v1
kind: Service
metadata:
  name: mastodon-nginx
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: mastodon-0.1.2
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: null
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: mastodon

