{{- $penpotDomainENV := split  ","  .Values.domain.penpot -}}
{{- $penpotDomain := index $penpotDomainENV "_0" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: penpot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penpot-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: penpot-backend
    spec:
      initContainers:
        - name: init-chmod-data
          image: "docker.io/beclab/busybox:1.37"
          command:
            - sh
            - -c
            - |
              chown -R 1001:1001 /opt/data/
          resources: {}
          volumeMounts:
            - name: data-assets
              mountPath: /opt/data/assets
              readOnly: false
          securityContext:
            runAsUser: 0
      containers:
        - name: penpot-backend
          image: "docker.io/beclab/penpotapp-backend:2.11.1"
          resources:
            requests:
              cpu: 10m
              memory: 800Mi
            limits:
              cpu: 500m
              memory: 1.5Gi
          volumeMounts:
            - name: data-assets
              mountPath: /opt/data/assets
              readOnly: false
          ports:
            - name: http
              containerPort: 6060
              protocol: TCP
          env:
            - name: PENPOT_FLAGS
              value: "enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server enable-secure-session-cookies"
            - name: PENPOT_DATABASE_URI
              value: "postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.penpot }}"
            - name: PENPOT_DATABASE_USERNAME
              value: "{{ .Values.postgres.username }}"
            - name: PENPOT_DATABASE_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: PENPOT_REDIS_URI
              value: "redis://penpot-redis:6379/0"
            - name: PENPOT_ASSETS_STORAGE_BACKEND
              value: "assets-fs"
            - name: PENPOT_STORAGE_ASSETS_FS_DIRECTORY
              value: "/opt/data/assets"
            - name: PENPOT_TELEMETRY_ENABLED
              value: "false"
            - name: PENPOT_PUBLIC_URI
              value: "https://{{ $penpotDomain }}"
            - name: PENPOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: penpot-secret
                  key: penpot-secret
          envFrom:
            - configMapRef:
                name: smtp-config
      volumes:
        - name: data-assets
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.userspace.appData }}/penpot/data/assets