{{- $documensoDomainENV := split "," .Values.domain.documenso -}}
{{- $documensoDomain := index $documensoDomainENV "_0" -}}
{{- $localDomain := $documensoDomain -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: documenso-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "3000"
  NEXTAUTH_URL: "https://{{$documensoDomain}}"
  NEXT_PUBLIC_WEBAPP_URL: "https://{{$documensoDomain}}"
  NEXT_PRIVATE_INTERNAL_WEBAPP_URL: "https://{{$documensoDomain}}"

  NEXT_PRIVATE_DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.documenso }}"
  NEXT_PRIVATE_DIRECT_DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.documenso }}"

  NEXT_PUBLIC_UPLOAD_TRANSPORT: ""
  NEXT_PRIVATE_UPLOAD_ENDPOINT: ""
  NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE: ""
  NEXT_PRIVATE_UPLOAD_REGION: ""
  NEXT_PRIVATE_UPLOAD_BUCKET: ""
  NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID: ""
  NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY: ""


  NEXT_PRIVATE_SMTP_FROM_ADDRESS: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_FROM_ADDRESS }}'
  NEXT_PRIVATE_SMTP_FROM_NAME: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_FROM_NAME }}'
  NEXT_PRIVATE_SMTP_HOST: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_HOST }}'
  NEXT_PRIVATE_SMTP_PASSWORD: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_PASSWORD }}'
  NEXT_PRIVATE_SMTP_PORT: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_PORT }}'
  NEXT_PRIVATE_SMTP_SECURE: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_SECURE }}'
  NEXT_PRIVATE_SMTP_USERNAME: '{{ .Values.olaresEnv.NEXT_PRIVATE_SMTP_USERNAME }}'
  NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS: "false"
  NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT: '50'
  NEXT_PRIVATE_SMTP_TRANSPORT: "smtp-auth"

  NEXT_PUBLIC_DISABLE_SIGNUP: "false"
  NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH: "/opt/documenso/cert.p12"