apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: astrbot
  name: astrbot
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: astrbot
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: astrbot
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Asia/Shanghai
        image: "docker.io/beclab/soulter-astrbot:v3.5.26"
        name: astrbot
        ports:
        - containerPort: 6185
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /AstrBot/data
          name: app-data-data
        - mountPath: /etc/localtime:ro
          name: app-data-etc-localtime
      restartPolicy: Always
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appData }}/data'
            {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/data'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/data'
          {{- end }}
          type: DirectoryOrCreate
        name: app-data-data
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appData }}/etc/localtime'
            {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/etc/localtime'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/etc/localtime'
          {{- end }}
          type: DirectoryOrCreate
        name: app-data-etc-localtime
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: astrbot
  name: astrbot
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: "6185"
    port: 6185
    targetPort: 6185
  selector:
    io.kompose.service: astrbot
