---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sillytavern-config
  namespace: '{{ .Release.Namespace }}'
data:
  config.yaml: |
    hostWhitelist:
      enabled: false
    logging:
      enableAccessLog: false
      minLogLevel: 2
