{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: v1
kind: Service
metadata:
  name: paddleocr-svc
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: paddleocr
spec:
  selector:
    io.kompose.service: paddleocr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sharedentrances-paddleocr
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: paddleocr
spec:
  selector:
    io.kompose.service: paddleocr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
