{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $whisperwebuiDomainENV := split "," .Values.domain.whisperservice -}}
{{- $whisperwebuiDomain := index $whisperwebuiDomainENV "_0" -}}
{{- $localDomain := $whisperwebuiDomain -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisperservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: whisperservice
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisperservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisperservice
    spec:
      containers:
        - name: whisperservice
          image: "docker.io/beclab/harveyff-whisperservice:v1.1.0"
          ports:
            - containerPort: 8000
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: HF_ENDPOINT
              value: "{{ .Values.olaresEnv.HF_ENDPOINT }}"
            - name: HF_TOKEN
              value: "{{ .Values.olaresEnv.HF_TOKEN }}"
          envFrom:
            - configMapRef:
                name: whisperapi-config
          command:
            - sh
            - "-c"
            - |
{{- if and (hasKey .Values "models") (gt (len .Values.models) 0) }}
{{- range $i, $model := .Values.models }}
              while [ ! -f /root/.cache/.success.{{ $model.name }} ]; do
                echo "Waiting for model file /root/.cache/.success.{{ $model.name }} ..."
                sleep 5
              done
{{- end }}
              echo "All model files are ready."
{{- end }}
              echo "Starting application..."
              gunicorn --bind 0.0.0.0:8000 --workers 1 --timeout 0 --log-config gunicorn_logging.conf app.main:app -k uvicorn.workers.UvicornWorker
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
            - name: models
              mountPath: /root/.cache
            - name: data
              mountPath: /tmp
      volumes:
        - name: models
          hostPath:
            path: "{{ .Values.userspace.userData }}/Huggingface/{{ .Release.Name }}"
            type: DirectoryOrCreate
        - name: data
          hostPath:
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/data"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/data"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/data"
            {{- end }}
            type: DirectoryOrCreate

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-download-models
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-downloadmodels
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-downloadmodels
    spec:
      containers:
        - name: {{ .Release.Name }}-downloadmodels
          image: "docker.io/beclab/downloader-init:v0.1.1"
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: whisperapi-config
          command: ["sh", "-c"]
          args:
            - |
{{- range $i, $model := .Values.models }}
              echo "${CDN_HOST}/{{ $model.name }} {{ $model.output }} {{ $model.md5 }}" {{ if eq $i 0 }} > {{ else }} >> {{ end }} /app/tasks/tasks.txt && \
{{- end }}
              /app/downloader-init /app/tasks/tasks.txt 8090 1 Whisper-API https://{{ $whisperwebuiDomain }}/health && \
              echo "Download finished..."
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: downloader-tmp-vol
              mountPath: /app/downloader-tmp
            - name: downloads-vol
              mountPath: /app/downloads
            - name: tasks-txt-vol
              mountPath: /app/tasks
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
      volumes:
        - name: downloader-tmp-vol
          hostPath:
            path: "{{ .Values.userspace.userData }}/Huggingface/{{ .Release.Name }}/download/temp"
            type: DirectoryOrCreate
        - name: downloads-vol
          hostPath:
            path: "{{ .Values.userspace.userData }}/Huggingface/{{ .Release.Name }}"
            type: DirectoryOrCreate
        - name: tasks-txt-vol
          emptyDir: {}
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: whisperservice-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: whisperservice
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: download-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-downloadmodels
  ports:
    - name: download-status
      port: 8090
      targetPort: 8090
  type: ClusterIP
{{- end }}
