{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hunyuan3dv21-config
  namespace: {{ .Release.Namespace }}
data:
  CDN_HOST: "{{ .Values.downloadCdnURL | default "https://cdn.olares.com" }}/models"
  DEFAULT_LANGUAGE: "zh"
 {{- end }}