{{- $deerflowDomainENV := split "," .Values.domain.deerflow -}}
{{- $deerflowDomain := index $deerflowDomainENV "_0" -}}
{{- $localDomain := $deerflowDomain -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deerflow-config
  namespace: {{ .Release.Namespace }}
data:
  NEXT_PUBLIC_API_URL: "https://{{$deerflowDomain}}/api"