## Cloudreve 配置
#cloudreve:
#  image: docker.io/beclab/cloudreve-cloudreve:3.8.3
#  port: 5212
#  uploadsPath: /cloudreve/uploads
#  avatarPath: /cloudreve/avatar
#  confPath: /cloudreve/conf.ini
#  dbPath: /cloudreve/cloudreve.db
#
## 持久化存储配置
#persistence:
#  enabled: true
#  storageClass: ""
#  accessModes: ReadWriteOnce
#  size: 10Gi