userspace:
  appdata: ""
  appCache: ""

timezone: Etc/UTC

rtspPassword: frigate

cacheSize: 4Gi

shmSize: 2Gi

securityContext:
  privileged: false

usb:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

