apiVersion: v1
kind: ConfigMap
metadata:
  name: stirlingpdf-config
  namespace: {{ .Release.Namespace }}
data:
  DOCKER_ENABLE_SECURITY: "false"
  SECURITY_ENABLELOGIN: "false"
  DISABLE_ADDITIONAL_FEATURES: "false"
  FAT_DOCKER: "true"
  SYSTEM_DEFAULTLOCALE: "en-US"
  SYSTEM_MAXFILESIZE: "200"
  METRICS_ENABLED: "true"
  SYSTEM_GOOGLEVISIBILITY: "true"
  showUpdate: "false"
#  appName: "Stirling-PDF Olares"
#  homeDescription: "Locally hosted web application that allows you to perform various operations on PDF files"
#  appNameNavbar: "Stirling-PDF Olares"