{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisperwebui-config
  namespace: {{ .Release.Namespace }}
data:
  whisper_type: "faster-whisper"
  CDN_HOST: "{{ .Values.downloadCdnURL | default "https://cdn.olares.com" }}/models"
{{- end }}