kind: ConfigMap
apiVersion: v1
metadata:
  name: litellm-config
  namespace: "{{ .Release.Namespace }}"
data:
  proxy_config.yaml: |
    general_settings:
      master_key: "{{ .Values.olaresEnv.LITELLM_MASTER_KEY }}"

    litellm_settings:
      callbacks: ["smtp_email"]
