apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: clawdbot
  name: clawdbot
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clawdbot
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: clawdbot
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Asia/Shanghai
        image: "ghcr.io/clawdbot/clawdbot:2026.1.24"
        name: clawdbot
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /app/workspace
          name: app-data-workspace
        - mountPath: /app/config
          name: app-data-config
      restartPolicy: Always
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appData }}/workspace'
            {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/workspace'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/workspace'
          {{- end }}
          type: DirectoryOrCreate
        name: app-data-workspace
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appData }}/config'
            {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/config'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appData }}/{{ .Release.Name }}/config'
          {{- end }}
          type: DirectoryOrCreate
        name: app-data-config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: clawdbot
  name: clawdbot
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: clawdbot
